// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDothpgVEx-9K8cP4MP7Sb6YjNP2_mKLLk',
    appId: '1:911782972979:android:12d6ca90b341f14a3c1d46',
    messagingSenderId: '911782972979',
    projectId: 'smart-expend',
    storageBucket: 'smart-expend.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbc35NUXhsyL0b1MeyC0SQmlvgdWgeccc',
    appId: '1:911782972979:web:fd4f95c2ffa27faa3c1d46',
    messagingSenderId: '911782972979',
    projectId: 'smart-expend',
    authDomain: 'smart-expend.firebaseapp.com',
    storageBucket: 'smart-expend.firebasestorage.app',
    measurementId: 'G-GKJJLKQBTB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYjXZq2FjzRPGImOHwVuDWb6Lnn1ljVIA',
    appId: '1:911782972979:ios:6168a97d4011c94f3c1d46',
    messagingSenderId: '911782972979',
    projectId: 'smart-expend',
    storageBucket: 'smart-expend.firebasestorage.app',
    iosBundleId: 'com.example.smartExpend',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYjXZq2FjzRPGImOHwVuDWb6Lnn1ljVIA',
    appId: '1:911782972979:ios:6168a97d4011c94f3c1d46',
    messagingSenderId: '911782972979',
    projectId: 'smart-expend',
    storageBucket: 'smart-expend.firebasestorage.app',
    iosBundleId: 'com.example.smartExpend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbc35NUXhsyL0b1MeyC0SQmlvgdWgeccc',
    appId: '1:911782972979:web:47495d9e6cf10a163c1d46',
    messagingSenderId: '911782972979',
    projectId: 'smart-expend',
    authDomain: 'smart-expend.firebaseapp.com',
    storageBucket: 'smart-expend.firebasestorage.app',
    measurementId: 'G-096CY1N9J4',
  );

}